// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace Escapa.Utility
{
public static class GooglePlayIds
{
        public const string leaderboard_medium = "CggIwq-mmkgQAhAI"; // <GPGSID>
        public const string leaderboard_easy = "CggIwq-mmkgQAhAH"; // <GPGSID>
        public const string achievement_panic_button = "CggIwq-mmkgQAhAB"; // <GPGSID>
        public const string achievement_moves_like_jagger = "CggIwq-mmkgQAhAE"; // <GPGSID>
        public const string achievement_black_hawk = "CggIwq-mmkgQAhAC"; // <GPGSID>
        public const string achievement_zen = "CggIwq-mmkgQAhAD"; // <GPGSID>
        public const string leaderboard_i_n_s_a_n_e = "CggIwq-mmkgQAhAK"; // <GPGSID>
        public const string leaderboard_hard = "CggIwq-mmkgQAhAJ"; // <GPGSID>

}
}
